version: '3'
services:
    app:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

    redis:
        image: redis:latest
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - laravel-network

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan queue:work
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

networks:
    laravel-network:

volumes:
    mysql-data:
